import React, { useRef, useState } from 'react';
import { Download, FileSpreadsheet, Upload } from 'lucide-react';
import { downloadImportTemplate } from '@/services/inventoryService';
import { Modal } from './SupplierList';
export default function ImportExport({ products, onImport }) {
 const ref=useRef(); const [rows,setRows]=useState([]); const [open,setOpen]=useState(false); const [error,setError]=useState('');
 const select=async(e)=>{const f=e.target.files?.[0];if(!f)return;try{const {inventoryService}=await import('@/services/inventoryService');const parsed=await inventoryService.parseImportFile(f);setRows(parsed);setError('');setOpen(true);}catch(err){setError(err.message);}e.target.value='';};
 const confirm=async()=>{await onImport(rows);setOpen(false);setRows([]);};
 const exportFile=async()=>{const {inventoryService}=await import('@/services/inventoryService');await inventoryService.exportProducts(products);};
 return <><div className="flex flex-wrap gap-2"><button onClick={exportFile} className="px-3 py-2 rounded-lg bg-[#FFD300] font-black text-xs flex gap-1 items-center"><FileSpreadsheet size={14}/> Export Excel</button><button disabled={!onImport} onClick={()=>ref.current?.click()} className="px-3 py-2 rounded-lg bg-[#090C11] text-white font-black text-xs flex gap-1 items-center"><Upload size={14}/> Import CSV/Excel</button><button onClick={downloadImportTemplate} className="px-3 py-2 rounded-lg border-2 border-[#090C11] bg-white font-black text-xs flex gap-1 items-center"><Download size={14}/> Download Template</button><input ref={ref} type="file" accept=".csv,.xlsx,.xls" onChange={select} hidden/>{error&&<span className="text-xs font-bold text-red-600">{error}</span>}</div>{open&&<Modal title={`Import Preview — ${rows.length} rows`} wide onClose={()=>setOpen(false)}><div className="max-h-[55vh] overflow-auto border border-gray-200"><table className="w-full text-xs"><thead className="bg-[#090C11] text-white sticky top-0"><tr>{Object.keys(rows[0]||{}).map(k=><th key={k} className="px-2 py-2 text-left">{k}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((r,i)=><tr key={i} className="border-b border-gray-100">{Object.values(r).map((v,j)=><td key={j} className="px-2 py-2 whitespace-nowrap">{String(v)}</td>)}</tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="px-4 py-2 rounded-lg border-2 border-gray-200 font-bold">Cancel</button><button disabled={!onImport} onClick={confirm} className="px-4 py-2 rounded-lg bg-[#FFD300] font-black">Import {rows.length} Rows</button></div></Modal>}</>;
}
