import React,{useRef,useState} from 'react';
import {AlertTriangle,Download,FileSpreadsheet,Upload} from 'lucide-react';
import {downloadImportTemplate} from '@/services/inventoryService';
import {Modal} from './SupplierList';

export default function ImportExport({products,onImport}){
 const ref=useRef(),[rows,setRows]=useState([]),[open,setOpen]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const select=async(e)=>{const file=e.target.files?.[0];if(!file)return;try{const {inventoryService}=await import('@/services/inventoryService');setRows(await inventoryService.parseImportFile(file));setResult(null);setError('');setOpen(true);}catch(err){setError(err?.message||'Unable to read import file.');}e.target.value='';};
 const confirm=async()=>{if(!onImport||!rows.length)return;setBusy(true);setError('');try{setResult(await onImport(rows));}catch(err){setError(err?.message||'Import failed.');}finally{setBusy(false);}};
 const close=()=>{setOpen(false);setRows([]);setResult(null);setError('');};
 const exportFile=async()=>{const {inventoryService}=await import('@/services/inventoryService');await inventoryService.exportProducts(products);};
 const errors=Array.isArray(result?.errors)?result.errors:[],processed=Number(result?.processed||0);
 return <><div className="flex flex-wrap gap-2"><button type="button" onClick={exportFile} className="px-3 py-2 rounded-lg bg-[var(--brand-primary)] text-[var(--action-text)] font-black text-xs flex gap-1 items-center"><FileSpreadsheet size={14}/>Export Excel</button><button type="button" disabled={!onImport} onClick={()=>ref.current?.click()} className="px-3 py-2 rounded-lg bg-[var(--brand-dark)] text-[var(--on-dark)] font-black text-xs flex gap-1 items-center disabled:opacity-50"><Upload size={14}/>Import CSV/Excel</button><button type="button" onClick={downloadImportTemplate} className="px-3 py-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] text-[var(--text)] font-black text-xs flex gap-1 items-center"><Download size={14}/>Download Template</button><input ref={ref} type="file" accept=".csv,.xlsx,.xls" onChange={select} hidden/>{error&&<span className="text-xs font-bold text-[var(--danger)] self-center">{error}</span>}</div>
 {open&&<Modal title={result?'Import Result':`Import Preview — ${rows.length} rows`} wide onClose={close}>{result?<div className="space-y-4"><div className="rounded-xl border border-[var(--border)] bg-[var(--brand-surface)] p-4"><div className="flex items-center gap-2 font-black text-[var(--text)]">{errors.length>0&&<AlertTriangle size={17} className="text-[var(--warning)]"/>}{processed} registered; {errors.length} rejected.</div><div className="mt-2 text-xs text-[var(--muted)]">Created: <b>{result?.created||0}</b> · Updated: <b>{result?.updated||0}</b> · Stock adjusted: <b>{result?.stock_adjusted||0}</b></div></div>{errors.length>0&&<div className="rounded-xl border border-[var(--border)] overflow-hidden"><div className="px-3 py-2 bg-[var(--brand-dark)] text-[var(--on-dark)] text-xs font-black">Import errors ({errors.length})</div><div className="max-h-[45vh] overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-[var(--surface)] border-b border-[var(--border)]"><tr><th className="px-3 py-2 text-left">#</th><th className="px-3 py-2 text-left">Name</th><th className="px-3 py-2 text-left">SKU</th><th className="px-3 py-2 text-left">Error</th></tr></thead><tbody>{errors.map((x,i)=><tr key={`${x?.sku||x?.name||'row'}-${i}`} className="border-b border-[var(--border)]"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2 font-semibold">{x?.name||'—'}</td><td className="px-3 py-2">{x?.sku||'—'}</td><td className="px-3 py-2 text-[var(--danger)]">{x?.error||'Unknown error'}</td></tr>)}</tbody></table></div></div>}<div className="flex justify-end"><button type="button" onClick={close} className="px-4 py-2 rounded-lg bg-[var(--brand-primary)] text-[var(--action-text)] font-black">Done</button></div></div>:<><div className="max-h-[55vh] overflow-auto border border-[var(--border)]"><table className="w-full text-xs"><thead className="bg-[var(--brand-dark)] text-[var(--on-dark)] sticky top-0"><tr>{Object.keys(rows[0]||{}).map(k=><th key={k} className="px-2 py-2 text-left">{k}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((row,i)=><tr key={i} className="border-b border-[var(--border)]">{Object.values(row).map((v,j)=><td key={j} className="px-2 py-2 whitespace-nowrap">{String(v??'')}</td>)}</tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={close} disabled={busy} className="px-4 py-2 rounded-lg border border-[var(--border)] font-bold">Cancel</button><button type="button" disabled={!onImport||busy} onClick={confirm} className="px-4 py-2 rounded-lg bg-[var(--brand-primary)] text-[var(--action-text)] font-black disabled:opacity-50">{busy?'Importing…':`Import ${rows.length} Rows`}</button></div></>}</Modal>}</>;
}