import React, { useEffect, useState } from 'react';
import { Search, ChevronDown } from 'lucide-react';
import ThemeToggle from '@/components/ui/ThemeToggle';
import { useAuth } from '@/lib/AuthContext';
import { tableLabel } from '@/data/mockData';

export default function TopBar({ moduleLabel, activeTable }) {
  const { user } = useAuth();
  const business = { name: user?.property?.name || user?.property?.business_name || 'Property' };
  const branch = { name: user?.property?.branch_name || user?.property?.city || '' };
  const [activeStaff,setActiveStaff]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('olitech_active_staff_v2')||'null')}catch{return null}});
  useEffect(()=>{const h=e=>setActiveStaff(e.detail||null);window.addEventListener('olitech:staff-changed',h);return()=>window.removeEventListener('olitech:staff-changed',h)},[]);
  const now = new Date(); const timeStr = now.toLocaleTimeString('en-KE',{hour:'2-digit',minute:'2-digit'}); const dateStr=now.toLocaleDateString('en-KE',{weekday:'short',day:'numeric',month:'short',year:'numeric'});
  const displayName=activeStaff?.full_name||user?.name||user?.email?.split('@')[0]||'Staff'; const displayRole=activeStaff?.role||user?.staff?.role||user?.propertyRole||user?.role||'Staff'; const avatar=activeStaff?.avatar||displayName.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  return <header className="flex items-center justify-between h-16 px-6 bg-[var(--surface)] text-[var(--text)] border-b border-[var(--border)] shrink-0 gap-4"><div className="flex items-center gap-4 min-w-0"><div className="min-w-0 shrink-0"><div className="font-semibold text-sm leading-tight truncate">{moduleLabel}</div>{activeTable&&<div className="text-xs mt-0.5 text-[var(--muted)] truncate">Table {tableLabel(activeTable)} · {activeTable.seats} seats</div>}</div><div className="hidden md:flex items-center gap-2 rounded-lg px-3 py-2 bg-[var(--bg)] border border-[var(--border)] w-64 lg:w-80 shrink-0"><Search size={15} className="text-[var(--muted)] shrink-0"/><input type="text" placeholder="Search tables, guests, orders…" className="bg-transparent text-sm outline-none flex-1 min-w-0 text-[var(--text)] placeholder:placeholder:text-[var(--muted)] border-0"/></div></div><div className="flex items-center gap-4 ml-auto flex-shrink-0"><button className="flex items-center gap-2 px-4 py-1.5 rounded-full text-sm bg-[var(--bg)] text-[var(--text)] border border-[var(--border)] max-w-[220px]"><span className="font-semibold truncate">{business.name}</span>{branch.name&&<><span className="text-[var(--muted)]">·</span><span className="text-[var(--muted)] truncate hidden lg:inline">{branch.name}</span></>}<ChevronDown size={14} className="text-[var(--muted)] shrink-0"/></button><div className="text-right hidden lg:block leading-tight"><div className="font-mono text-sm font-bold">{timeStr}</div><div className="text-xs text-[var(--muted)]">{dateStr}</div></div><div className="flex items-center gap-2 pl-4 border-l border-[var(--border)] min-w-0"><div className="w-9 h-9 rounded-full bg-[var(--action)] text-[var(--action-text)] flex items-center justify-center text-xs font-bold shrink-0">{avatar}</div><div className="hidden sm:block min-w-0"><div className="text-xs font-semibold leading-tight truncate max-w-[130px]">{displayName}</div><div className="text-xs text-[var(--muted)] truncate max-w-[130px]">{displayRole}</div></div><ThemeToggle compact /></div></div></header>;
}
