import React, { useEffect, useState } from 'react';
import { Search, ChevronDown } from 'lucide-react';
import { CURRENT_USER, BUSINESSES, BRANCHES } from '@/data/platformData';
import { tableLabel } from '@/data/mockData';

export default function TopBar({ moduleLabel, activeTable }) {
  const business = BUSINESSES[0]; const branch = BRANCHES.b1[0];
  const [activeStaff,setActiveStaff]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('olitech_active_staff_v2')||'null')}catch{return null}});
  useEffect(()=>{const h=e=>setActiveStaff(e.detail||null);window.addEventListener('olitech:staff-changed',h);return()=>window.removeEventListener('olitech:staff-changed',h)},[]);
  const now = new Date(); const timeStr = now.toLocaleTimeString('en-KE',{hour:'2-digit',minute:'2-digit'}); const dateStr=now.toLocaleDateString('en-KE',{weekday:'short',day:'numeric',month:'short',year:'numeric'});
  const displayName=activeStaff?.full_name||CURRENT_USER.name; const displayRole=activeStaff?.role||CURRENT_USER.role; const avatar=activeStaff?.avatar||displayName.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  return <header className="flex items-center justify-between h-16 px-6 bg-white text-[#111827] border-b border-[#E5E7EB] shrink-0 gap-4"><div className="flex items-center gap-4 min-w-0"><div className="min-w-0 shrink-0"><div className="font-semibold text-sm leading-tight truncate">{moduleLabel}</div>{activeTable&&<div className="text-xs mt-0.5 text-[#6B7280] truncate">Table {tableLabel(activeTable)} · {activeTable.seats} seats</div>}</div><div className="hidden md:flex items-center gap-2 rounded-lg px-3 py-2 bg-[#F3F4F6] border border-[#E5E7EB] w-64 lg:w-80 shrink-0"><Search size={15} className="text-[#757B81] shrink-0"/><input type="text" placeholder="Search tables, guests, orders…" className="bg-transparent text-sm outline-none flex-1 min-w-0 text-[#111827] placeholder:text-[#9CA3AF] border-0"/></div></div><div className="flex items-center gap-4 ml-auto flex-shrink-0"><button className="flex items-center gap-2 px-4 py-1.5 rounded-full text-sm bg-[#F3F4F6] text-[#111827] border border-[#E5E7EB] max-w-[220px]"><span className="font-semibold truncate">{business.name}</span><span className="text-[#757B81]">·</span><span className="text-[#6B7280] truncate hidden lg:inline">{branch.name}</span><ChevronDown size={14} className="text-[#757B81] shrink-0"/></button><div className="text-right hidden lg:block leading-tight"><div className="font-mono text-sm font-bold">{timeStr}</div><div className="text-xs text-[#757B81]">{dateStr}</div></div><div className="flex items-center gap-2 pl-4 border-l border-[#E5E7EB] min-w-0"><div className="w-9 h-9 rounded-full bg-[#FFD300] text-[#090C11] flex items-center justify-center text-xs font-bold shrink-0">{avatar}</div><div className="hidden sm:block min-w-0"><div className="text-xs font-semibold leading-tight truncate max-w-[130px]">{displayName}</div><div className="text-xs text-[#757B81] truncate max-w-[130px]">{displayRole}</div></div></div></div></header>;
}
