/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      opacity: Object.fromEntries(Array.from({ length: 101 }, (_, i) => [i, `${i / 100}`])),
      borderRadius: {
        lg: 'var(--radius)',
        md: 'var(--radius-control)',
        sm: '4px',
      },
      boxShadow: {
        card: 'var(--shadow)',
        overlay: 'var(--shadow-overlay)',
      },
      colors: {
        brand: {
          dark: 'var(--brand-dark)',
          charcoal: 'var(--brand-charcoal)',
          primary: 'var(--action)',
          hover: 'var(--action-hover)',
          soft: 'var(--brand-soft)',
        },
        action: { DEFAULT: 'var(--action)', hover: 'var(--action-hover)', foreground: 'var(--action-text)' },
        info: 'var(--info)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        surface: { DEFAULT: 'var(--surface)', secondary: 'var(--surface-2)' },
        text: { DEFAULT: 'var(--text)', muted: 'var(--muted)' },
        primaryHex: 'var(--action)',
        champagne: 'var(--action)',
        sunflower: 'var(--action)',
        yellowLight: 'var(--brand-soft)',
        warm: 'var(--bg)',
        surfaceSecondary: 'var(--surface-2)',
        divider: 'var(--border)',
        borderStrong: 'var(--border-strong)',
        textPrimary: 'var(--text)',
        textSecondary: 'var(--muted)',
        deepBlack: 'var(--brand-dark)',
        charcoal: 'var(--brand-charcoal)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        primary: { DEFAULT: 'var(--primary)', foreground: 'var(--primary-foreground)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        muted: { DEFAULT: 'var(--surface-2)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--info)', '2': 'var(--success)', '3': 'var(--warning)',
          '4': 'var(--danger)', '5': 'var(--room-charge)',
        },
        sidebar: {
          DEFAULT: 'var(--brand-charcoal)', foreground: 'var(--text)',
          primary: 'var(--action)', 'primary-foreground': 'var(--action-text)',
          accent: 'var(--surface-2)', 'accent-foreground': 'var(--text)',
          border: 'var(--border)', ring: 'var(--ring)',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)'],
        body: ['var(--font-body)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'ui-xs': ['12px', { lineHeight: '16px' }],
        'ui-sm': ['13px', { lineHeight: '18px' }],
        'ui-base': ['14px', { lineHeight: '20px' }],
        'ui-lg': ['16px', { lineHeight: '24px' }],
        'ui-xl': ['20px', { lineHeight: '28px' }],
        'ui-2xl': ['24px', { lineHeight: '32px' }],
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
