import { supabase } from '@/lib/supabaseClient';
const clean=(v)=>String(v ?? '').trim();
export const phase2CatalogueService={
 async listModifierGroups(propertyId){const {data,error}=await supabase.from('pos_modifier_groups').select('*,options:pos_modifier_options(*)').eq('property_id',propertyId).order('sort_order').order('name');if(error)throw new Error(error.message);return data||[];},
 async saveModifierGroup(propertyId,input){const name=clean(input.name);if(!name)throw new Error('Modifier group name is required.');const {data,error}=await supabase.from('pos_modifier_groups').upsert({id:input.id||undefined,property_id:propertyId,name,selection_type:input.selectionType||'single',required:!!input.required,min_selections:Number(input.minSelections||0),max_selections:Number(input.maxSelections||1),active:input.active!==false,sort_order:Number(input.sortOrder||0)},{onConflict:'id'}).select('*').single();if(error)throw new Error(error.message);await supabase.from('pos_modifier_options').delete().eq('property_id',propertyId).eq('modifier_group_id',data.id);const options=(input.options||[]).filter(o=>clean(o.name)).map((o,i)=>({property_id:propertyId,modifier_group_id:data.id,name:clean(o.name),price_delta_minor:Number(o.priceDeltaMinor||0),active:o.active!==false,sort_order:Number(o.sortOrder??i)}));if(options.length){const r=await supabase.from('pos_modifier_options').insert(options);if(r.error)throw new Error(r.error.message);}return data;},
 async deleteModifierGroups(propertyId,ids){const {error}=await supabase.from('pos_modifier_groups').delete().eq('property_id',propertyId).in('id',ids);if(error)throw new Error(error.message);},
 async listDiscounts(propertyId){const {data,error}=await supabase.from('pos_discounts').select('*').eq('property_id',propertyId).order('name');if(error)throw new Error(error.message);return data||[];},
 async saveDiscount(propertyId,input){const type=input.discountType||'percentage';const payload={id:input.id||undefined,property_id:propertyId,name:clean(input.name),code:clean(input.code)||null,discount_type:type,percentage_basis_points:type==='percentage'?Number(input.percentageBasisPoints||0):null,amount_minor:type==='fixed'?Number(input.amountMinor||0):null,scope:input.scope||'order',active:input.active!==false,starts_at:input.startsAt||null,ends_at:input.endsAt||null};if(!payload.name)throw new Error('Discount name is required.');const {data,error}=await supabase.from('pos_discounts').upsert(payload,{onConflict:'id'}).select('*').single();if(error)throw new Error(error.message);return data;},
 async deleteDiscounts(propertyId,ids){const {error}=await supabase.from('pos_discounts').delete().eq('property_id',propertyId).in('id',ids);if(error)throw new Error(error.message);},
 async listSuppliers(propertyId){const {data,error}=await supabase.from('suppliers').select('id,name,contact,phone,email,products_supplied,created_at').eq('property_id',propertyId).order('name');if(error)throw new Error(error.message);return data||[];},
 async saveSupplier(propertyId,input){const payload={property_id:propertyId,name:clean(input.name),contact:clean(input.contact)||null,phone:clean(input.phone)||null,email:clean(input.email)||null,products_supplied:clean(input.productsSupplied)||null};if(!payload.name)throw new Error('Supplier name is required.');const q=input.id?supabase.from('suppliers').update(payload).eq('id',input.id).eq('property_id',propertyId):supabase.from('suppliers').insert(payload);const {data,error}=await q.select('*').single();if(error)throw new Error(error.message);return data;},
 async deleteSuppliers(propertyId,ids){const {error}=await supabase.from('suppliers').delete().eq('property_id',propertyId).in('id',ids);if(error)throw new Error(error.message);}
};