import React,{useEffect,useState} from 'react';
import {Building2,Plus,Trash2} from 'lucide-react';
import {supabase} from '@/lib/supabaseClient';
import {usePrinterStore} from '@/data/modules/printerStoreV2';

export default function StoresPage(){
 const {stores}=usePrinterStore(); const [editing,setEditing]=useState(null); const [name,setName]=useState(''); const [address,setAddress]=useState('');
 useEffect(()=>{supabase.from('stores').select('*').order('is_default',{ascending:false}).order('name').then(({data})=>{if(data) usePrinterStore.setState({stores:data})});},[]);
 const save=async()=>{if(!name.trim())return;const payload={name:name.trim(),address:address.trim()||null};if(!editing){payload.workspace_id=stores[0]?.workspace_id;payload.property_id=stores[0]?.property_id;}let q=editing?supabase.from('stores').update(payload).eq('id',editing):supabase.from('stores').insert(payload);const {data,error}=await q.select().single();if(!error){usePrinterStore.setState(s=>({stores:editing?s.stores.map(x=>x.id===editing?data:x):[...s.stores,data]}));setEditing(null);setName('');setAddress('')}};
 const remove=async(id)=>{if(!window.confirm('Delete this store?'))return;const {error}=await supabase.from('stores').delete().eq('id',id);if(!error)usePrinterStore.setState(s=>({stores:s.stores.filter(x=>x.id!==id)}))};
 return <div className="min-h-full bg-[#F5F5F5] p-6"><div className="mx-auto max-w-5xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-normal text-[#212121]">Stores</h2><p className="text-sm text-[#757575]">Manage properties/outlets and their printer configuration.</p></div><button onClick={()=>{setEditing(null);setName('');setAddress('')}} className="bg-[#4CAF50] px-5 py-3 text-sm font-medium uppercase text-white">+ Add store</button></div>
 <div className="grid gap-4 md:grid-cols-[1fr_320px]"><div className="bg-white shadow-sm">{stores.map(s=><div key={s.id} className="flex items-center gap-4 border-b p-5 last:border-0"><Building2 className="text-[#78909C]"/><div className="flex-1"><div className="font-medium text-[#212121]">{s.name}{s.is_default&&<span className="ml-2 text-xs text-[#4CAF50]">Default</span>}</div><div className="text-xs text-[#757575]">{s.address||'No address'}</div></div><button onClick={()=>{setEditing(s.id);setName(s.name);setAddress(s.address||'')}} className="text-sm text-[#2E7D32]">Edit</button><button onClick={()=>remove(s.id)} className="text-[#D32F2F]"><Trash2 size={17}/></button></div>)}{!stores.length&&<p className="p-8 text-sm text-[#757575]">No stores configured.</p>}</div>
 <div className="bg-white p-5 shadow-sm"><h3 className="font-medium text-[#212121]">{editing?'Edit store':'New store'}</h3><label className="mt-4 block text-xs text-[#757575]">Store name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full border-b border-[#BDBDBD] px-0 py-2 outline-none focus:border-[#4CAF50]"/></label><label className="mt-4 block text-xs text-[#757575]">Address<input value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 w-full border-b border-[#BDBDBD] px-0 py-2 outline-none focus:border-[#4CAF50]"/></label><button onClick={save} className="mt-6 w-full bg-[#4CAF50] py-3 text-sm font-medium uppercase text-white">{editing?'Save changes':'Create store'}</button></div></div></div></div>;
}
