import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Boxes, ClipboardList, FileSpreadsheet, Package, Plus, Search } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/lib/AuthContext';
import { inventoryService, STORE_CATEGORIES, STORE_LOCATIONS, STORE_UNITS } from '@/services/inventoryService';
import ProductTable from '@/components/store/ProductTable';
import StockAlerts from '@/components/store/StockAlerts';
import SupplierList from '@/components/store/SupplierList';
import ImportExport from '@/components/store/ImportExport';
import StockMovements from '@/components/store/StockMovements';
import UsageForm from '@/components/store/UsageForm';
import { Modal } from '@/components/store/SupplierList';
import { getSessionStaff } from '@/services/authService';

const TABS = [
  ['overview','Stock Overview'], ['products','Products'], ['suppliers','Suppliers'], ['purchases','Purchases / GRN'], ['usage','Stock Usage'], ['alerts','Alerts'],
];
const ROLES = ['store_manager','fb_manager','general_manager','admin','owner','administrator','manager','front_office_manager','hotel_admin','super_admin'];
const normalizeRole = (r) => String(r || '').toLowerCase().replace(/\s+/g,'_');

export default function Store() {
  const { user } = useAuth();
  const propertyId = user?.property?.id;
  const sessionStaff = getSessionStaff();
  const role = normalizeRole(sessionStaff?.role || user?.staff?.role || user?.propertyRole || user?.role);
  const allowed = ROLES.includes(role) || user?.isPlatformOwner;
  const isFnbManager = role === 'fb_manager';
  const showCost = ['store_manager','fb_manager','hotel_admin','super_admin','owner','admin','administrator','manager'].includes(role) || user?.isPlatformOwner;
  const readOnly = role === 'front_office_manager';
  const canWrite = !readOnly && ['store_manager','fb_manager','hotel_admin','super_admin','owner','admin','administrator','manager'].includes(role);
  const [tab,setTab]=useState('overview');
  const [products,setProducts]=useState([]), [suppliers,setSuppliers]=useState([]), [movements,setMovements]=useState([]), [alerts,setAlerts]=useState([]), [purchases,setPurchases]=useState([]);
  const [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [search,setSearch]=useState(''), [category,setCategory]=useState('all'), [location,setLocation]=useState('all');
  const [productModal,setProductModal]=useState(null); const [reportFrom,setReportFrom]=useState(''); const [reportTo,setReportTo]=useState(''); const [reportCategory,setReportCategory]=useState('all');

  const load = useCallback(async()=>{ if(!propertyId)return; setLoading(true); try { const filterCategory=isFnbManager?'F&B':category; const [ps,ss,ms,as,po]=await Promise.all([inventoryService.listProducts(propertyId,{category:filterCategory,location,search}),inventoryService.listSuppliers(propertyId),inventoryService.listMovements(propertyId),inventoryService.getAlerts(propertyId),inventoryService.listPurchases(propertyId)]); setProducts(ps);setSuppliers(ss);setMovements(ms);setAlerts(as);setPurchases(po);setError(''); } catch(e){setError(e.message);} finally{setLoading(false);} },[propertyId,category,location,search,isFnbManager]);
  useEffect(()=>{load();},[load]);
  const stats=useMemo(()=>({total:products.length,low:products.filter(p=>Number(p.current_stock)>0&&Number(p.current_stock)<=Number(p.min_stock)).length,out:products.filter(p=>Number(p.current_stock)<=0).length,value:products.reduce((s,p)=>s+Number(p.current_stock||0)*Number(p.cost_price||0),0)}),[products]);
  const filteredProducts=useMemo(()=>products.filter(p=>!isFnbManager||p.category==='F&B'),[products,isFnbManager]);

  if(!allowed) return <div className="flex-1 bg-[#F5F3EF] flex items-center justify-center p-6"><div className="max-w-md text-center bg-white border-2 border-[#090C11] rounded-2xl p-8"><Package className="mx-auto mb-3"/><h2 className="text-xl font-black">Store access restricted</h2><p className="text-sm text-gray-500 mt-2">Store / Controls is available to Store Managers, F&B Managers, General Managers and Administrators.</p></div></div>;

  const addProduct=async(form)=>{try{await inventoryService.createProduct({...form,category:isFnbManager?'F&B':form.category,property_id:propertyId,current_stock:Number(form.current_stock)||0,min_stock:Number(form.min_stock)||0,max_stock:Number(form.max_stock)||0,cost_price:Number(form.cost_price)||0,selling_price:Number(form.selling_price)||0});toast.success('Product added.');setProductModal(null);load();}catch(e){toast.error(e.message);}};
  const editProduct=async(form)=>{try{await inventoryService.updateProduct(form.id,{...form,category:isFnbManager?'F&B':form.category,current_stock:Number(form.current_stock)||0,min_stock:Number(form.min_stock)||0,max_stock:Number(form.max_stock)||0,cost_price:Number(form.cost_price)||0,selling_price:Number(form.selling_price)||0,supplier_id:form.supplier_id||null});toast.success('Product updated.');setProductModal(null);load();}catch(e){toast.error(e.message);}};
  const importRows=async(rows)=>{try{await inventoryService.bulkUpsertProducts(propertyId,rows);toast.success(`${rows.length} products imported / updated.`);load();}catch(e){toast.error(e.message);throw e;}};
  const addSupplier=async(f)=>{await inventoryService.createSupplier({propertyId,...f});toast.success('Supplier added.');load();};
  const recordUsage=async(f)=>{await inventoryService.recordUsage({propertyId,...f});load();};
  const report=async()=>{try{const ms=await inventoryService.listMovements(propertyId,{from:reportFrom,to:reportTo,category:reportCategory});await inventoryService.exportStockReport(ms,`olitechs-stock-report-${reportFrom||'all'}-${reportTo||'today'}.xlsx`);}catch(e){toast.error(e.message);}};

  return <div className="flex-1 min-h-0 overflow-y-auto bg-[#F5F3EF] p-4 lg:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><Package size={22}/><h1 className="text-2xl font-black">Store / Controls</h1>{isFnbManager&&<span className="text-[10px] font-black px-2 py-1 rounded-full bg-[#FFD300]">F&B ONLY</span>}</div><p className="text-sm text-gray-500 mt-1">Inventory, suppliers, purchasing, usage and stock alerts.</p></div><ImportExport products={filteredProducts} onImport={canWrite ? importRows : null}/></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{[['Total Products',stats.total,Boxes,'black'],['Low Stock',stats.low,AlertTriangle,'yellow'],['Out of Stock',stats.out,AlertTriangle,'red'],['Stock Value',readOnly?'Restricted':`KES ${stats.value.toLocaleString('en-KE')}`,FileSpreadsheet,'green']].map(([l,v,I,c])=><div key={l} className="bg-white border-2 border-[#090C11] rounded-2xl p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-widest font-black">{l}</span><I size={17} className={c==='red'?'text-red-600':c==='yellow'?'text-yellow-600':c==='green'?'text-green-600':''}/></div><div className="text-2xl font-black mt-2">{v}</div></div>)}</div>
    <div className="flex gap-1 overflow-x-auto mb-4 bg-white border-2 border-[#090C11] rounded-xl p-1">{TABS.map(([id,label])=><button key={id} disabled={readOnly && ['purchases','usage'].includes(id)} onClick={()=>setTab(id)} className="px-4 py-2.5 rounded-lg text-xs font-black whitespace-nowrap" style={{background:tab===id?'#FFD300':'#fff',color:'#090C11'}}>{label}{id==='alerts'&&alerts.length>0?<span className="ml-1.5 rounded-full bg-red-600 text-white px-1.5 py-0.5">{alerts.length}</span>:null}</button>)}</div>
    {error&&<div className="mb-4 rounded-xl bg-red-50 border-2 border-red-200 text-red-700 p-3 text-sm font-bold">{error}</div>}
    {loading?<div className="p-12 text-center font-bold text-gray-500">Loading Store…</div>:<>
      {tab==='overview'&&<Overview products={filteredProducts} alerts={alerts} movements={movements} onAlerts={()=>setTab('alerts')}/>} 
      {tab==='products'&&<><Filters search={search} setSearch={setSearch} category={category} setCategory={setCategory} location={location} setLocation={setLocation} fnb={isFnbManager}/><div className="mt-4"><ProductTable products={filteredProducts} onEdit={canWrite ? setProductModal : undefined} onAdd={canWrite ? ()=>setProductModal({}) : undefined} showCost={showCost}/></div></>}
      {tab==='suppliers'&&<SupplierList suppliers={suppliers} onAdd={canWrite ? addSupplier : undefined}/>} 
      {tab==='purchases'&&canWrite&&<PurchasePanel propertyId={propertyId} products={filteredProducts} suppliers={suppliers} onSaved={load}/>} 
      {tab==='usage'&&canWrite&&<div className="space-y-4"><UsageForm products={filteredProducts} onSubmit={recordUsage}/><StockMovements movements={movements.filter(m=>String(m.reason||'').toLowerCase().includes('usage'))}/></div>}
      {tab==='alerts'&&<div className="space-y-4"><StockAlerts alerts={alerts}/><ReportBar from={reportFrom} setFrom={setReportFrom} to={reportTo} setTo={setReportTo} category={reportCategory} setCategory={setReportCategory} onExport={report}/></div>}
    </>}
    {productModal!==null&&<ProductModal value={productModal} suppliers={suppliers} fnbOnly={isFnbManager} onClose={()=>setProductModal(null)} onSave={productModal.id?editProduct:addProduct}/>} 
  </div>;
}

function Filters({search,setSearch,category,setCategory,location,setLocation,fnb}){return <div className="flex flex-wrap gap-2 bg-white border-2 border-[#090C11] rounded-xl p-3"><div className="flex items-center gap-2 border-2 border-gray-200 rounded-lg px-3 flex-1 min-w-[220px]"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product or SKU…" className="py-2 w-full outline-none text-sm"/></div><select disabled={fnb} value={fnb?'F&B':category} onChange={e=>setCategory(e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2 text-sm font-bold">{!fnb&&<option value="all">All Categories</option>}{STORE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><select value={location} onChange={e=>setLocation(e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2 text-sm font-bold"><option value="all">All Locations</option>{STORE_LOCATIONS.map(x=><option key={x}>{x}</option>)}</select></div>}

function Overview({products,alerts,movements,onAlerts}){return <div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2"><ProductTable products={products.slice(0,12)} onEdit={()=>{}} showCost={showCost} /></div><div><StockAlerts alerts={alerts.slice(0,8)}/>{alerts.length>8&&<button onClick={onAlerts} className="mt-2 text-xs font-black underline">View all alerts</button>}<div className="mt-4"><StockMovements movements={movements.slice(0,10)}/></div></div></div>}

function ProductModal({value,suppliers,fnbOnly=false,onClose,onSave}){const [f,setF]=useState({sku:'',name:'',category:fnbOnly?'F&B':'F&B',unit:'bottle',current_stock:0,min_stock:5,max_stock:100,cost_price:0,selling_price:0,supplier_id:'',location:'Main Store',expiry_date:'',...value});const set=(k,v)=>setF({...f,[k]:v});return <Modal title={value.id?'Edit Product':'Add Product'} wide onClose={onClose}><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{[['sku','SKU'],['name','Name *'],['current_stock','Current Stock'],['min_stock','Min Stock'],['max_stock','Max Stock'],['cost_price','Cost Price'],['selling_price','Selling Price'],['expiry_date','Expiry Date']].map(([k,l])=><label key={k} className="text-xs font-black">{l}<input type={['current_stock','min_stock','max_stock','cost_price','selling_price'].includes(k)?'number':k==='expiry_date'?'date':'text'} value={f[k]??''} onChange={e=>set(k,e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5 outline-none"/></label>)}<label className="text-xs font-black">Category<select disabled={fnbOnly} value={fnbOnly?'F&B':f.category} onChange={e=>set('category',e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5">{STORE_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-black">Unit<select value={f.unit} onChange={e=>set('unit',e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5">{STORE_UNITS.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-black">Location<select value={f.location} onChange={e=>set('location',e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5">{STORE_LOCATIONS.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-black">Supplier<select value={f.supplier_id||''} onChange={e=>set('supplier_id',e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5"><option value="">No supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button onClick={()=>onSave(f)} disabled={!f.name} className="mt-5 w-full py-3 rounded-xl bg-[#FFD300] font-black">{value.id?'Save Changes':'Create Product'}</button></Modal>}

function PurchasePanel({propertyId,products,suppliers,onSaved}){const [supplierId,setSupplierId]=useState(''),[invoice,setInvoice]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[lines,setLines]=useState([{productId:'',qty:1,costPrice:0}]);const update=(i,k,v)=>setLines(lines.map((l,n)=>n===i?{...l,[k]:v}:l));const save=async()=>{try{await inventoryService.createPurchase({propertyId,supplierId,invoiceNo:invoice,purchaseDate:date,lines});toast.success('GRN / stock in posted.');setLines([{productId:'',qty:1,costPrice:0}]);onSaved();}catch(e){toast.error(e.message);}};return <div className="bg-white border-2 border-[#090C11] rounded-2xl p-4"><div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><label className="text-xs font-black">Supplier<select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5"><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-xs font-black">Invoice No.<input value={invoice} onChange={e=>setInvoice(e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5"/></label><label className="text-xs font-black">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5"/></label></div><div className="mt-5 space-y-2">{lines.map((l,i)=><div key={i} className="grid grid-cols-[1fr_100px_130px] gap-2"><select value={l.productId} onChange={e=>update(i,'productId',e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" min="1" value={l.qty} onChange={e=>update(i,'qty',e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2" placeholder="Qty"/><input type="number" min="0" value={l.costPrice} onChange={e=>update(i,'costPrice',e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2" placeholder="Cost"/></div>)}</div><div className="flex gap-2 mt-4"><button onClick={()=>setLines([...lines,{productId:'',qty:1,costPrice:0}])} className="px-4 py-2 rounded-lg border-2 border-[#090C11] font-black text-xs"><Plus size={14} className="inline"/> Add line</button><button onClick={save} className="px-5 py-2 rounded-lg bg-[#FFD300] font-black text-xs">Post Stock In / GRN</button></div><div className="mt-6 border-t-2 border-[#090C11] pt-4"><h3 className="font-black mb-2">Recent Purchases</h3><div className="text-xs text-gray-500">Use the Stock Movements tab below for the audit trail.</div></div></div>}

function ReportBar({from,setFrom,to,setTo,category,setCategory,onExport}){return <div className="bg-white border-2 border-[#090C11] rounded-2xl p-4"><div className="flex items-center gap-2 mb-3"><ClipboardList size={17}/><h3 className="font-black">Export Stock Report</h3></div><div className="flex flex-wrap gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2 text-sm"/><select value={category} onChange={e=>setCategory(e.target.value)} className="border-2 border-gray-200 rounded-lg px-3 py-2 text-sm"><option value="all">All Categories</option>{STORE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><button onClick={onExport} className="px-4 py-2 rounded-lg bg-[#FFD300] font-black text-xs flex items-center gap-1"><FileSpreadsheet size={14}/> Export Stock Report</button></div></div>}
