import React,{useState} from 'react';
import {Shirt} from 'lucide-react';
import {useAuth} from '@/lib/AuthContext';
import {pmsService} from '@/services/pmsService';
import {useQueryClient} from '@tanstack/react-query';
import {pmsQueryKeys,usePmsLaundryQuery} from '@/hooks/usePmsQuery';
const B='#E5E5E5',S='#FFF',S2='#F2F2F2',T='#090C11',M='#757B81',Y='#FFD300';const flow={received:'washing',washing:'ready',ready:'delivered'};
export default function Laundry(){const{user}=useAuth(),propertyId=user?.property?.id;const queryClient=useQueryClient();const ordersQuery=usePmsLaundryQuery(propertyId);const orders=ordersQuery.data||[];const[guest,setGuest]=useState(''),[room,setRoom]=useState(''),[item,setItem]=useState('Laundry item'),[qty,setQty]=useState('1'),[price,setPrice]=useState('0'),[error,setError]=useState('');
const invalidate=()=>queryClient.invalidateQueries({queryKey:pmsQueryKeys.laundry(propertyId)});const create=async()=>{if(!guest.trim())return setError('Guest name is required.');try{await pmsService.createLaundryOrder({propertyId,guestName:guest,items:[{name:item,qty:Number(qty)}],total:Number(price)*Number(qty),notes:room?'Room '+room:null});setGuest('');setRoom('');setError('');await invalidate()}catch(e){setError(e.message)}};const advance=async o=>{if(!flow[o.status])return;try{await pmsService.updateLaundryOrder({orderId:o.id,status:flow[o.status]});await invalidate()}catch(e){setError(e.message)}};

return <div className="flex-1 overflow-y-auto p-4" style={{background:'#F8F8F7'}}><div className="grid lg:grid-cols-3 gap-4"><section className="rounded-2xl p-4" style={{background:S,border:'1px solid '+B}}><div className="flex gap-2 mb-4"><Shirt size={18}/><h2 className="text-sm font-black uppercase">New Laundry</h2></div><input value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Guest name" className="w-full p-2.5 rounded-lg mb-2 text-sm" style={{background:S2,border:'1px solid '+B}}/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Room number" className="w-full p-2.5 rounded-lg mb-2 text-sm" style={{background:S2,border:'1px solid '+B}}/><input value={item} onChange={e=>setItem(e.target.value)} placeholder="Item/service" className="w-full p-2.5 rounded-lg mb-2 text-sm" style={{background:S2,border:'1px solid '+B}}/><div className="grid grid-cols-2 gap-2"><input type="number" value={qty} onChange={e=>setQty(e.target.value)} className="p-2.5 rounded-lg text-sm" style={{background:S2,border:'1px solid '+B}}/><input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Unit price" className="p-2.5 rounded-lg text-sm" style={{background:S2,border:'1px solid '+B}}/></div>{(error||ordersQuery.error)&&<p className="text-xs text-red-600 mt-3">{error||ordersQuery.error?.message}</p>}<button onClick={create} className="w-full mt-4 py-3 rounded-xl font-black" style={{background:Y,color:T}}>Create Laundry Order</button></section><section className="lg:col-span-2 rounded-2xl overflow-hidden" style={{background:S,border:'1px solid '+B}}><div className="p-4 border-b" style={{borderColor:B}}><h2 className="text-sm font-black uppercase">Laundry Queue</h2></div>{ordersQuery.isLoading?<div className="p-4 text-xs" style={{color:M}}>Loading laundry queue…</div>:orders.map(o=><div key={o.id} className="p-4 flex items-center gap-3 border-b" style={{borderColor:B}}><div className="flex-1"><div className="text-sm font-bold">{o.guest_name||'Guest'} · {o.notes||'No room'}</div><div className="text-xs mt-1" style={{color:M}}>{o.status} · {Number(o.total).toFixed(2)} · {new Date(o.created_at).toLocaleString()}</div></div>{flow[o.status]&&<button onClick={()=>advance(o)} className="px-3 py-2 rounded-lg text-xs font-black" style={{background:Y}}>Mark {flow[o.status]}</button>}</div>)}</section></div></div>}