import React from 'react';
import { CheckCircle2, ClipboardCheck, RefreshCw, AlertTriangle } from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { pmsService } from '@/services/pmsService';

const money=(v)=>`KES ${Number(v||0).toLocaleString('en-KE',{maximumFractionDigits:2})}`;
const btn='inline-flex items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold disabled:opacity-50';
const input='w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200';

export default function NightAudit(){
 const {user}=useAuth(); const propertyId=user?.property?.id;
 const [businessDate,setBusinessDate]=React.useState(null),[check,setCheck]=React.useState(null),[history,setHistory]=React.useState([]),[notes,setNotes]=React.useState('');
 const [loading,setLoading]=React.useState(true),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[done,setDone]=React.useState(null);
 const load=React.useCallback(async()=>{if(!propertyId)return;setLoading(true);setError('');try{const d=await pmsService.getBusinessDate(propertyId);setBusinessDate(d);const [p,h]=await Promise.all([pmsService.getNightAuditPrecheck(propertyId,d),pmsService.listNightAudits(propertyId)]);setCheck(p);setHistory(h)}catch(e){setError(e.message||'Unable to load night audit.')}finally{setLoading(false)}},[propertyId]);
 React.useEffect(()=>{load()},[load]);
 const run=async()=>{setBusy(true);setError('');try{const a=await pmsService.runNightAudit({propertyId,notes});setDone(a);setNotes('');await load()}catch(e){setError(e.message||'Night audit could not be completed.')}finally{setBusy(false)}};
 return <div className="flex-1 overflow-y-auto bg-[#f8f8f7] p-4 lg:p-6"><div className="mx-auto max-w-[1250px] space-y-4">
  <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold">Night Audit</h1><p className="mt-1 text-sm text-slate-500">Reconcile the business day, verify cashier closure, then roll to the next business date.</p></div><button className={btn+' border border-slate-200 bg-white'} onClick={load} disabled={loading||busy}><RefreshCw size={15}/> Refresh</button></header>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {done&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={18}/> Business day {done.business_date} closed successfully.</div><div className="mt-1">Next business date: <strong>{done.next_business_date}</strong>.</div></div>}
  <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><ClipboardCheck size={20}/><div><h2 className="font-bold">Pre-audit reconciliation</h2><p className="text-sm text-slate-500">Business date: <strong>{businessDate||'—'}</strong></p></div></div>
   <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="POS transactions" value={check?.transactions??'—'}/><Metric label="POS revenue" value={money(check?.revenue)}/><Metric label="Open cashier shifts" value={check?.open_cashier_shifts??'—'} bad={Number(check?.open_cashier_shifts)>0}/><Metric label="Pending adjustments" value={check?.pending_adjustments??'—'} bad={Number(check?.pending_adjustments)>0}/></div>
   <div className={`mt-4 rounded-lg border p-3 text-sm ${check?.ready?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-amber-200 bg-amber-50 text-amber-800'}`}><div className="flex items-center gap-2 font-semibold">{check?.ready?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>} {check?.ready?'All cashier controls are reconciled and the day is ready to close.':'Resolve all open cashier shifts and pending adjustments before closing the business day.'}</div></div>
   <label className="mt-4 block text-xs font-semibold text-slate-600">Night audit notes<textarea className={input+' mt-1'} rows="3" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record any operational or reconciliation notes for this business day."/></label>
   <button className={btn+' mt-3 bg-[#FFD300] text-slate-950'} disabled={busy||loading||!check?.ready} onClick={run}><CheckCircle2 size={15}/> Close business day</button>
  </section>
  <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Night audit history</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-slate-200 text-left text-[10px] uppercase tracking-wide text-slate-500"><th className="px-3 py-2">Business date</th><th className="px-3 py-2">Revenue</th><th className="px-3 py-2">Cash</th><th className="px-3 py-2">Card</th><th className="px-3 py-2">M-Pesa</th><th className="px-3 py-2">Refunds</th><th className="px-3 py-2">Variance</th><th className="px-3 py-2">Closed</th></tr></thead><tbody>{history.map(a=><tr key={a.id} className="border-b border-slate-100"><td className="px-3 py-3 font-semibold">{a.business_date}</td><td className="px-3 py-3 font-mono">{money(a.total_revenue)}</td><td className="px-3 py-3 font-mono">{money(a.cash_revenue)}</td><td className="px-3 py-3 font-mono">{money(a.card_revenue)}</td><td className="px-3 py-3 font-mono">{money(a.mpesa_revenue)}</td><td className="px-3 py-3 font-mono">{money(a.refunds)}</td><td className="px-3 py-3 font-mono">{money(a.cashier_variance)}</td><td className="px-3 py-3 text-xs text-slate-500">{new Date(a.completed_at).toLocaleString('en-KE')}</td></tr>)}{!history.length&&<tr><td colSpan="8" className="px-3 py-8 text-center text-sm text-slate-500">No completed night audits yet.</td></tr>}</tbody></table></div></section>
 </div></div>
}
function Metric({label,value,bad}){return <div className={`rounded-lg border p-3 ${bad?'border-red-200 bg-red-50':'border-slate-200 bg-slate-50'}`}><div className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</div><div className={`mt-1 text-lg font-bold ${bad?'text-red-700':'text-slate-950'}`}>{value}</div></div>}
