import React,{useEffect,useState}from'react';
import{CreditCard,RefreshCw}from'lucide-react';
import{useAuth}from'@/lib/AuthContext';
import{pmsService}from'@/services/pmsService';
export default function SubscriptionPanel(){
 const{user}=useAuth(),propertyId=user?.property?.id,[form,setForm]=useState({planCode:'starter',status:'trial',trialEndsAt:'',currentPeriodEndsAt:'',graceEndsAt:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{if(!propertyId){setLoading(false);return}try{const x=await pmsService.getSubscription(propertyId);if(x)setForm({planCode:x.plan_code||'starter',status:x.status||'trial',trialEndsAt:x.trial_ends_at?.slice(0,16)||'',currentPeriodEndsAt:x.current_period_ends_at?.slice(0,16)||'',graceEndsAt:x.grace_ends_at?.slice(0,16)||''})}catch(e){setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[propertyId]);
 const save=async()=>{try{setSaving(true);await pmsService.upsertSubscription({propertyId,planCode:form.planCode,status:form.status,trialEndsAt:form.trialEndsAt||null,currentPeriodEndsAt:form.currentPeriodEndsAt||null,graceEndsAt:form.graceEndsAt||null});setMsg('Subscription updated.')}catch(e){setMsg(e.message)}finally{setSaving(false)}};
 if(loading)return <div className="p-6"><RefreshCw className="animate-spin"/></div>;
 if(!propertyId)return <div className="p-5 text-sm text-[#757B81]">Select a property to manage its subscription.</div>;
 return <div className="p-4"><div className="max-w-xl rounded-2xl border bg-white p-5"><div className="flex items-center gap-3 mb-5"><div className="h-10 w-10 rounded-xl bg-[#FFD300] flex items-center justify-center"><CreditCard size={18}/></div><div><h2 className="font-black">Subscription & Paywall</h2><p className="text-xs text-[#757B81]">Control this property's subscription access.</p></div></div><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">Plan<select className="mt-1 w-full rounded-xl border p-2" value={form.planCode} onChange={e=>setForm({...form,planCode:e.target.value})}><option>starter</option><option>professional</option><option>enterprise</option></select></label><label className="text-xs font-bold">Status<select className="mt-1 w-full rounded-xl border p-2" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['trial','active','past_due','suspended','cancelled'].map(x=><option key={x}>{x}</option>)}</select></label>{[['trialEndsAt','Trial ends'],['currentPeriodEndsAt','Current period ends'],['graceEndsAt','Grace ends']].map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input type="datetime-local" className="mt-1 w-full rounded-xl border p-2" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button disabled={saving} onClick={save} className="mt-5 rounded-xl bg-[#FFD300] px-4 py-2 text-sm font-black">{saving?'Saving…':'Save subscription'}</button>{msg&&<p className="mt-3 text-xs text-[#757B81]">{msg}</p>}</div></div>;
}