import React, { useState } from 'react';
import { Plus, X } from 'lucide-react';
export default function SupplierList({ suppliers, onAdd }) {
  const [open,setOpen]=useState(false); const [form,setForm]=useState({name:'',contact:'',phone:'',email:'',productsSupplied:''});
  const save=async()=>{if(!form.name)return;await onAdd(form);setForm({name:'',contact:'',phone:'',email:'',productsSupplied:''});setOpen(false);};
  return <div className="bg-white border-2 border-[#090C11] rounded-2xl overflow-hidden"><div className="flex justify-between items-center px-4 py-3 border-b-2 border-[#090C11]"><span className="text-xs font-black uppercase tracking-widest">Suppliers</span><button onClick={()=>setOpen(true)} className="px-3 py-2 rounded-lg bg-[#FFD300] font-black text-xs flex gap-1 items-center"><Plus size={14}/> Add Supplier</button></div><div className="overflow-auto"><table className="w-full"><thead className="bg-[#090C11] text-white"><tr>{['Name','Contact','Phone','Email','Products Supplied'].map(h=><th key={h} className="text-left px-4 py-2 text-[10px] uppercase">{h}</th>)}</tr></thead><tbody>{suppliers.map(s=><tr key={s.id} className="border-b border-gray-200"><td className="px-4 py-3 font-black">{s.name}</td><td className="px-4 py-3">{s.contact||'—'}</td><td className="px-4 py-3">{s.phone||'—'}</td><td className="px-4 py-3">{s.email||'—'}</td><td className="px-4 py-3">{s.products_supplied||'—'}</td></tr>)}</tbody></table></div>
    {open&&<Modal title="Add Supplier" onClose={()=>setOpen(false)}><Form fields={form} setFields={setForm}/><button onClick={save} className="w-full mt-4 py-3 rounded-xl bg-[#FFD300] font-black">Save Supplier</button></Modal>}
  </div>;
}
function Form({fields,setFields}){return <div className="grid grid-cols-2 gap-3">{[['name','Name *'],['contact','Contact person'],['phone','Phone'],['email','Email'],['productsSupplied','Products supplied']].map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input value={fields[k]} onChange={e=>setFields({...fields,[k]:e.target.value})} className="mt-1 w-full border-2 border-gray-200 rounded-lg px-3 py-2.5 outline-none"/></label>)}</div>}
export function Modal({title,onClose,children,wide=false}){return <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className={`bg-white rounded-2xl border-2 border-[#090C11] shadow-2xl p-5 w-full ${wide?'max-w-5xl':'max-w-xl'}`}><div className="flex items-center justify-between mb-4"><h3 className="font-black text-lg">{title}</h3><button onClick={onClose} className="p-2 rounded-lg hover:bg-gray-100"><X size={18}/></button></div>{children}</div></div>}
