import React,{useState} from 'react';
import {Outlet,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {ChevronDown,ChevronRight,LogOut} from 'lucide-react';
import {BACK_OFFICE_NAV,normalizeAppRole} from '@/data/modules/navArchitecture';
import {useAuth} from '@/lib/AuthContext';
import {getSessionStaff,normalizeStaffRole} from '@/services/authService';
import TopAppNav from './TopAppNav';
function roleOf(user){const s=getSessionStaff();return normalizeAppRole(s?.role||user?.staff?.role||user?.propertyRole||user?.role);}
export default function BackOfficeLayout(){
 const {user,logout}=useAuth(),loc=useLocation(),nav=useNavigate(),role=roleOf(user);
 const [open,setOpen]=useState({items:true,inventory:true,employees:true,settings:true,reports:false,integrations:false}),[owner,setOwner]=useState(false);
 const allowed=x=>{if(['admin','owner','store_manager'].includes(role))return true;if(role==='pos_staff')return ['items','inventory'].includes(x.id);if(role==='accountant')return x.id==='reports';return false;};
 return <div className="flex h-screen flex-col overflow-hidden bg-[#F5F5F5]"><TopAppNav/><div className="flex min-h-0 flex-1"><aside className="flex w-[280px] shrink-0 flex-col border-r border-[#E0E0E0] bg-white">
  <div className="border-b border-[#E0E0E0] px-4 py-3"><button onClick={()=>setOwner(v=>!v)} className="flex w-full items-center gap-3 text-left"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#8BC34A] text-xs font-bold text-white">O</div><div className="min-w-0 flex-1"><div className="text-sm font-medium text-[#212121]">Owner</div><div className="truncate text-xs text-[#757575]">{user?.email||'visiwawatamu@gmail.com'}</div></div><ChevronDown size={16}/></button>{owner&&<div className="mt-2 border border-[#E0E0E0] bg-white shadow-sm"><button onClick={()=>nav('/backoffice/account')} className="block w-full px-4 py-2 text-left text-sm hover:bg-[#F5F5F5]">Account</button><button onClick={logout} className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm text-[#D32F2F] hover:bg-[#FFF5F5]"><LogOut size={14}/>Sign out</button></div>}</div>
  <nav className="min-h-0 flex-1 overflow-y-auto py-2">{BACK_OFFICE_NAV.filter(allowed).map(sec=>{const I=sec.icon,has=!!sec.children?.length,active=sec.children?.some(([,p])=>loc.pathname===p||loc.pathname.startsWith(p+'/'))||(sec.path&&(loc.pathname===sec.path||loc.pathname.startsWith(sec.path+'/')));return <div key={sec.id} className="mb-1"><div className="flex items-center"><NavLink to={sec.path||sec.children?.[0]?.[1]||'#'} className={['flex min-h-11 flex-1 items-center gap-3 px-5 text-[14px]',active?'bg-[#F1F1F1] text-[#212121] font-medium':'text-[#424242] hover:bg-[#FAFAFA]'].join(' ')}><I size={20} style={{color:sec.color||'#616161'}}/><span>{sec.label}</span></NavLink>{has&&<button onClick={()=>setOpen(v=>({...v,[sec.id]:!v[sec.id]}))} className="px-4 text-[#757575]">{open[sec.id]?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</button>}{sec.notification&&<span className="mr-4 h-2 w-2 rounded-full bg-[#E53935]"/>}</div>{has&&open[sec.id]&&<div className="pb-1">{sec.children.map(([label,path])=><NavLink key={path} to={path} className={({isActive})=>['block py-2 pl-14 pr-4 text-[13px]',isActive?'bg-[#F1F1F1] font-medium text-[#212121]':'text-[#616161] hover:bg-[#FAFAFA]'].join(' ')}>{label}</NavLink>)}</div>}</div>})}</nav>
  <div className="border-t border-[#E0E0E0] bg-[#FFF8E1] p-3"><div className="text-[12px] font-medium text-[#424242]">Your free trial for employee management expires in 1 day.</div><button className="mt-1 text-[12px] font-bold text-[#4CAF50]">ACTIVATE SUBSCRIPTION</button></div>
 </aside><main className="min-w-0 flex-1 overflow-auto"><Outlet/></main></div></div>;
}
