import React,{useState}from"react";
import{Link}from"react-router-dom";
import{Building2,Mail,Lock,User,Eye,EyeOff,Loader2}from"lucide-react";
import{useAuth}from"@/lib/AuthContext";

const Field=({id,label,Icon,type="text",value,onChange,placeholder,autoComplete,show,onToggle})=><div><label htmlFor={id} className="mb-1.5 block text-[11px] font-bold text-[#374151]">{label}</label><div className="relative"><Icon className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#9CA3AF]" size={16}/><input id={id} type={type} autoComplete={autoComplete} placeholder={placeholder} value={value} onChange={onChange} required className="h-11 w-full rounded-xl border border-[#E5E7EB] pl-10 pr-12 text-sm outline-none focus:border-[#FFC400] focus:ring-4 focus:ring-[#FFC400]/15"/>{onToggle&&<button type="button" onClick={onToggle} className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2 text-[#6B7280]" aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={15}/>:<Eye size={15}/>}</button>}</div></div>;

export default function Register(){
 const{register}=useAuth();const[name,setName]=useState("");const[businessName,setBusinessName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[show,setShow]=useState(false);const[showConfirm,setShowConfirm]=useState(false);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[confirmationEmail,setConfirmationEmail]=useState(null);
 const submit=async e=>{e.preventDefault();if(loading)return;setError("");if(password!==confirmPassword)return setError("Passwords do not match");if(password.length<6)return setError("Password must be at least 6 characters");setLoading(true);try{const result=await register({name,email,password,businessName});if(result?.needsEmailConfirmation)setConfirmationEmail(result.email||email)}catch(err){console.error("[Register] registration failed:",err);setError(err.message||"Failed to create account. Please try again.")}finally{setLoading(false)}};
 const shell=(body)=><main className="flex min-h-screen items-center justify-center bg-[#F7F6F3] px-4 py-8 sm:px-6"><div className="w-full max-w-[1120px] overflow-hidden rounded-[28px] bg-[#121418] shadow-[0_28px_70px_rgba(18,20,24,.18)]"><div className="grid min-h-[620px] md:grid-cols-[3fr_2fr]"><section className="relative flex min-h-[300px] items-center overflow-hidden px-7 py-10 text-white sm:px-12 lg:px-16 md:min-h-[620px]"><div className="absolute -bottom-28 -left-24 h-72 w-72 rounded-full bg-[#FFC400]/10"/><div className="relative z-10"><div className="mb-10 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#FFC400] text-[#121418]"><Building2 size={26}/></div><div><div className="text-sm font-black">OliTechs</div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-white/50">PMS & POS</div></div></div><p className="mb-3 text-[11px] font-black uppercase tracking-[.28em] text-[#FFC400]">WELCOME</p><h1 className="text-3xl font-black leading-[1.08] sm:text-4xl lg:text-5xl">Welcome to OliTechs PMS & POS</h1><p className="mt-5 max-w-lg text-sm leading-7 text-white/65 sm:text-base">Manage your hotel operations, reservations, and point of sale from one powerful dashboard.</p></div></section><section className="relative flex items-center bg-[#121418] px-4 py-7 sm:px-8 md:-ml-12 md:py-10 lg:px-10"><div className="w-full rounded-[24px] border border-[#E5E7EB] bg-white p-6 text-[#121418] shadow-[0_24px_55px_rgba(0,0,0,.18)] sm:p-8">${body}</div></section></div></div></main>;
 if(confirmationEmail)return shell(<><h2 className="text-2xl font-black sm:text-3xl">Check your email</h2><p className="mt-2 text-xs text-[#6B7280]">We sent a confirmation link to {confirmationEmail}.</p><div className="mt-6 rounded-xl bg-[#FAFAF8] p-5 text-center text-sm leading-6 text-[#6B7280]">Click the link in that email to verify your address, then sign in. Your property application has already been submitted and will remain pending until the OliTechs administrator reviews it.</div><p className="mt-6 text-center text-xs text-[#6B7280]">Already confirmed? <Link to="/login" className="font-black underline decoration-[#FFC400]">Sign in</Link></p></>);
 return shell(<><h2 className="text-2xl font-black sm:text-3xl">Sign up</h2><p className="mt-2 text-xs text-[#6B7280]">Create your OliTechs PMS & POS account and submit your property application.</p>{error&&<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<form onSubmit={submit} className="mt-5 space-y-3.5"><Field id="name" label="Full name" Icon={User} autoComplete="name" placeholder="Jane Doe" value={name} onChange={e=>setName(e.target.value)}/><Field id="businessName" label="Property / hotel name" Icon={Building2} autoComplete="organization" placeholder="Your hotel or property" value={businessName} onChange={e=>setBusinessName(e.target.value)}/><Field id="email" label="Email" Icon={Mail} type="email" autoComplete="email" placeholder="you@hotel.com" value={email} onChange={e=>setEmail(e.target.value)}/><Field id="password" label="Password" Icon={Lock} type={show?"text":"password"} autoComplete="new-password" placeholder="Create a password" value={password} onChange={e=>setPassword(e.target.value)} show={show} onToggle={()=>setShow(v=>!v)}/><Field id="confirm" label="Confirm password" Icon={Lock} type={showConfirm?"text":"password"} autoComplete="new-password" placeholder="Repeat your password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} show={showConfirm} onToggle={()=>setShowConfirm(v=>!v)}/><button disabled={loading} className="flex h-11 w-full items-center justify-center rounded-xl bg-[#FFC400] text-sm font-black text-[#121418] hover:bg-[#FFD60A] disabled:opacity-60">{loading?<><Loader2 className="mr-2 animate-spin" size={17}/>Creating account...</>:"Sign up"}</button></form><p className="mt-6 text-center text-xs text-[#6B7280]">Already have an account? <Link to="/login" className="font-black underline decoration-[#FFC400] decoration-2 underline-offset-4">Sign in</Link></p></>);
}