import React,{useEffect,useState}from'react';
import{CalendarDays,Download,Printer}from'lucide-react';
import{useAuth}from'@/lib/AuthContext';
import{shiftService,exportShiftToExcel}from'@/services/shiftService';
import{getPrinters,getAssignments,printShiftReport}from'@/services/printService';
import{supabase}from'@/lib/supabaseClient';

export default function ShiftReport(){
 const{user}=useAuth();const propertyId=user?.property?.id;const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Nairobi'}).format(new Date());const[shifts,setShifts]=useState([]);const[error,setError]=useState('');
 useEffect(()=>{if(propertyId)shiftService.listShifts(propertyId).then(setShifts).catch(e=>setError(e.message));},[propertyId]);
 const action=async(s,type)=>{try{const report=await shiftService.getShiftReport(s.id);report.propertyId=propertyId;if(type==='excel')return exportShiftToExcel(report);const{data:settings}=await supabase.from('property_settings').select('*').eq('property_id',propertyId).maybeSingle();report.settings=settings;const[printers,assignments]=await Promise.all([getPrinters(propertyId),getAssignments(propertyId)]);const printer=assignments.filter(a=>a.assignment_type==='shift_reports'||a.assignment_type==='reports').map(a=>printers.find(p=>p.id===a.printer_id)).find(Boolean);if(!printer)throw new Error('No shift report printer assigned.');await printShiftReport(report,printer);}catch(e){setError(e.message||'Shift report action failed.')}};
 return <div className="flex-1 overflow-y-auto bg-[#F9F9FA] p-5"><div className="mx-auto max-w-5xl"><div className="mb-5 flex items-center justify-between"><div><div className="text-xl font-black text-slate-950">Shift Reports</div><div className="text-sm text-slate-500">Closing receipts and Excel sales breakdowns.</div></div><div className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold"><CalendarDays size={15}/>{date}</div></div>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border bg-white">{shifts.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-b p-4 last:border-b-0"><div><div className="font-black text-slate-950">{s.shift_no}</div><div className="text-xs text-slate-500">{s.status} · {new Date(s.opened_at).toLocaleString('en-KE')}</div></div><div className="flex gap-2"><button onClick={()=>action(s,'print')} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><Printer size={15}/>Re-print</button><button onClick={()=>action(s,'excel')} className="inline-flex items-center gap-2 rounded-xl bg-[#0E7482] px-3 py-2 text-xs font-bold text-white"><Download size={15}/>Export Excel</button></div></div>)}{!shifts.length&&<div className="p-10 text-center text-sm text-slate-500">No shifts recorded.</div>}</div></div></div>;
}