create or replace function public.fn_management_report(p_property_id uuid,p_from date,p_to date)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare v_days integer;v_sellable_rooms integer:=0;v_available_room_nights numeric:=0;v_occupied_room_nights numeric:=0;v_room_revenue numeric:=0;v_pos_gross numeric:=0;v_pos_tax numeric:=0;v_discounts numeric:=0;v_refunds numeric:=0;v_voids numeric:=0;v_inventory_value numeric:=0;v_purchases numeric:=0;v_consumption numeric:=0;v_wastage numeric:=0;v_arrivals integer:=0;v_departures integer:=0;v_reservations integer:=0;v_cash_variance numeric:=0;v_open_shifts integer:=0;v_closed_shifts integer:=0;v_total_stock_movements integer:=0;v_transfer_orders integer:=0;
begin
if p_property_id is null or p_from is null or p_to is null or p_from>p_to then raise exception 'Invalid reporting period'; end if;
if not public.is_platform_owner() and not public.is_member_of_property(p_property_id) then raise exception 'Not authorized'; end if;
v_days:=(p_to-p_from)+1;
select count(*) into v_sellable_rooms from public.rooms where property_id=p_property_id and active=true and status not in ('maintenance','out_of_service','blocked');
v_available_room_nights:=v_sellable_rooms*v_days;
with stay_days as (select distinct r.room_id,d::date as stay_date from public.reservations r cross join lateral generate_series(greatest(r.arrival,p_from)::timestamp,least(r.departure-1,p_to)::timestamp,interval '1 day') d where r.property_id=p_property_id and r.status<>'cancelled' and r.room_id is not null and r.arrival<=p_to and r.departure>p_from)
select count(*) into v_occupied_room_nights from stay_days;
select coalesce(sum(greatest(0,(least(r.departure,p_to+1)-greatest(r.arrival,p_from)))*coalesce(r.rate,0)),0) into v_room_revenue from public.reservations r where r.property_id=p_property_id and r.status<>'cancelled' and r.arrival<p_to+1 and r.departure>p_from;
select count(*) into v_reservations from public.reservations where property_id=p_property_id and status<>'cancelled' and arrival<=p_to and departure>p_from;
select count(*) into v_arrivals from public.reservations where property_id=p_property_id and status<>'cancelled' and arrival between p_from and p_to;
select count(*) into v_departures from public.reservations where property_id=p_property_id and status<>'cancelled' and departure between p_from and p_to;
select coalesce(sum(total),0),coalesce(sum(vat),0),coalesce(sum(discount_amount),0) into v_pos_gross,v_pos_tax,v_discounts from public.pos_receipts where property_id=p_property_id and status='posted' and (created_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select coalesce(sum(amount),0) into v_refunds from public.cashier_refunds where property_id=p_property_id and (created_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select coalesce(sum(total),0) into v_voids from public.pos_receipts where property_id=p_property_id and status='voided' and (voided_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select coalesce(sum(total),0) into v_purchases from public.purchase_orders where property_id=p_property_id and status<>'cancelled' and purchase_date between p_from and p_to;
select coalesce(sum(qty),0) into v_consumption from public.stock_usage where property_id=p_property_id and usage_date between p_from and p_to;
select coalesce(sum(quantity),0) into v_wastage from public.inventory_wastage where property_id=p_property_id and (created_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select coalesce(sum(current_stock*cost_price),0) into v_inventory_value from public.products where property_id=p_property_id;
select count(*) filter(where status='open'),count(*) filter(where status='closed'),coalesce(sum(variance) filter(where status='closed'),0) into v_open_shifts,v_closed_shifts,v_cash_variance from public.cashier_shifts where property_id=p_property_id and (opened_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select count(*) into v_total_stock_movements from public.stock_movements where property_id=p_property_id and (created_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
select count(*) into v_transfer_orders from public.stock_transfers where property_id=p_property_id and (created_at at time zone 'Africa/Nairobi')::date between p_from and p_to;
return jsonb_build_object('from',p_from,'to',p_to,'days',v_days,'hotel',jsonb_build_object('sellable_rooms',v_sellable_rooms,'available_room_nights',v_available_room_nights,'occupied_room_nights',v_occupied_room_nights,'occupancy_percent',case when v_available_room_nights=0 then 0 else round(v_occupied_room_nights/v_available_room_nights*100,2) end,'room_revenue',round(v_room_revenue,2),'adr',case when v_occupied_room_nights=0 then 0 else round(v_room_revenue/v_occupied_room_nights,2) end,'revpar',case when v_available_room_nights=0 then 0 else round(v_room_revenue/v_available_room_nights,2) end,'reservations',v_reservations,'arrivals',v_arrivals,'departures',v_departures),'sales',jsonb_build_object('pos_gross',round(v_pos_gross,2),'pos_tax',round(v_pos_tax,2),'discounts',round(v_discounts,2),'refunds',round(v_refunds,2),'voids',round(v_voids,2),'pos_net',round(v_pos_gross-v_refunds,2)),'inventory',jsonb_build_object('valuation',round(v_inventory_value,2),'purchases',round(v_purchases,2),'consumption_qty',round(v_consumption,2),'wastage_qty',round(v_wastage,2),'stock_movements',v_total_stock_movements,'transfer_orders',v_transfer_orders),'cashier',jsonb_build_object('open_shifts',v_open_shifts,'closed_shifts',v_closed_shifts,'cash_variance',round(v_cash_variance,2)));
end;$$;