import React,{useEffect,useMemo,useState} from 'react';
import {CloudOff,Plus,Search,Printer,Wifi,RefreshCw} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {usePrinterStore} from '@/data/modules/printerStore';
import {supabase} from '@/lib/supabaseClient';
import {inventoryService} from '@/services/inventoryService';
import {useAuth} from '@/lib/AuthContext';

export default function KitchenPrintersPage(){
 const {user}=useAuth(); const {stores,printerGroups,printers,printAgents,hydrate,addPrinterGroup,updatePrinterGroup,deletePrinterGroup,addPrinter,pairPrinter}=usePrinterStore();
 const [storeId,setStoreId]=useState(''),[categories,setCategories]=useState([]),[modal,setModal]=useState(null),[name,setName]=useState(''),[selectedCats,setSelectedCats]=useState([]),[selectedPrinters,setSelectedPrinters]=useState([]),[query,setQuery]=useState(''),[ip,setIp]=useState(''),[port,setPort]=useState('9100'),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.from('stores').select('*').order('is_default',{ascending:false}).order('name').then(({data,error})=>{if(error)toast.error(error.message);else if(data?.length){usePrinterStore.setState({stores:data});setStoreId(data.find(x=>x.is_default)?.id||data[0].id)}})},[]);
 const store=stores.find(s=>s.id===storeId);
 useEffect(()=>{if(storeId)hydrate(storeId)},[storeId,hydrate]);
 useEffect(()=>{if(!store?.property_id)return;inventoryService.listPosCategories(store.property_id).then(rows=>setCategories((rows||[]).map(c=>({id:c.id,name:c.name})))).catch(()=>setCategories([]))},[store?.property_id]);
 const openNew=()=>{setModal({mode:'new'});setName('');setSelectedCats([]);setSelectedPrinters([])};
 const openEdit=g=>{setModal({mode:'edit',id:g.id});setName(g.name);setSelectedCats(g.categoryIds||[]);setSelectedPrinters(g.printerIds||[])};
 const save=async()=>{if(!name.trim())return;setBusy(true);try{if(modal.mode==='new')await addPrinterGroup({name,categoryIds:selectedCats,printerIds:selectedPrinters});else await updatePrinterGroup({id:modal.id,name,categoryIds:selectedCats,printerIds:selectedPrinters});toast.success('Printer group saved');setModal(null)}catch(e){toast.error(e.message)}finally{setBusy(false)}};
 const addManual=async()=>{if(!ip.trim())return;try{await addPrinter({name:'Network Printer '+ip,ipAddress:ip.trim(),port:Number(port)||9100,isKitchen:true});toast.success('Printer added');setIp('')}catch(e){toast.error(e.message)}};
 const testPrint=async(p)=>{try{const res=await fetch('http://127.0.0.1:8631/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({host:p.ip_address,port:p.port||9100})});const data=await res.json();if(!data.ok)throw new Error(data.message||'Test print failed');toast.success('Test print sent')}catch(e){toast.error('Print Agent Offline — '+(e.message||'unable to print'))}};
 const discover=async()=>{try{const res=await fetch('http://127.0.0.1:8631/discover');const data=await res.json();if(!data.ok)throw new Error(data.message);for(const p of data.printers||[])await addPrinter({name:p.label||p.host,ipAddress:p.host,port:p.port,isKitchen:true});toast.success(`${data.printers?.length||0} printer(s) discovered`)}catch(e){toast.error('Print Agent Offline — '+(e.message||''))}};
 const visibleCats=useMemo(()=>{const q=query.toLowerCase().trim();return q?categories.filter(c=>c.name.toLowerCase().includes(q)):categories},[categories,query]);
 return <div className="bg-white shadow-[0_1px_3px_rgba(0,0,0,.2)]">
  <div className="border-b border-[#E0E0E0] px-6 py-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-normal text-[#212121]">Kitchen printers</h2><p className="mt-1 text-sm text-[#757575]">Route menu categories to physical printers by store.</p></div><button onClick={openNew} className="h-11 bg-[#8BC34A] px-5 text-sm font-medium uppercase text-white shadow-sm">+ Add printer group</button></div><div className="mt-5 flex items-center gap-3"><label className="text-xs font-medium uppercase text-[#757575]">Store</label><select value={storeId} onChange={e=>setStoreId(e.target.value)} className="h-10 min-w-[260px] border border-[#D6D6D6] bg-white px-3 text-sm outline-none focus:border-[#4CAF50]">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div>
  <table className="w-full border-collapse"><thead><tr className="h-14 border-b border-[#E0E0E0] text-left text-sm text-[#757575]"><th className="w-14 pl-6"><Checkbox aria-label="Select all"/></th><th>Name</th><th className="pr-8 text-right">Categories</th></tr></thead><tbody>{printerGroups.map(g=><tr key={g.id} onClick={()=>openEdit(g)} className="h-[68px] cursor-pointer border-b border-[#E0E0E0] hover:bg-[#FAFAFA]"><td className="pl-6"><Checkbox onClick={e=>e.stopPropagation()} aria-label={`Select ${g.name}`}/></td><td className="text-[15px] text-[#212121]">{g.name}</td><td className="pr-8 text-right text-[15px] text-[#424242]">{g.categoryCount||0}</td></tr>)}</tbody></table>{!printerGroups.length&&<div className="p-8 text-sm text-[#757575]">No printer groups for this store.</div>}
  <section className="border-t-8 border-[#F5F5F5] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-normal text-[#212121]">Physical Printers</h3><p className="text-xs text-[#757575]">Print Agent status and physical printer endpoints.</p></div><div className="flex gap-2"><button onClick={discover} className="flex items-center gap-2 border border-[#CFCFCF] px-4 py-2 text-sm"><RefreshCw size={15}/>Discover printers</button><button onClick={addManual} className="flex items-center gap-2 border border-[#CFCFCF] px-4 py-2 text-sm"><Plus size={15}/>Add manual IP</button></div></div>
  <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="border border-[#E0E0E0] p-4"><div className="text-xs uppercase text-[#757575]">Print Agent</div><div className="mt-2 font-medium text-[#212121]">{printAgents.some(a=>a.status==='online')?'Online':'Offline'}</div><div className="text-xs text-[#9E9E9E]">{printAgents[0]?.discovered_printers||0} discovered</div></div><div className="md:col-span-2 border border-[#E0E0E0] p-4"><div className="mb-2 text-xs uppercase text-[#757575]">Add manual IP</div><div className="flex gap-2"><input value={ip} onChange={e=>setIp(e.target.value)} placeholder="192.168.1.50" className="flex-1 border px-3 py-2 text-sm"/><input value={port} onChange={e=>setPort(e.target.value)} className="w-24 border px-3 py-2 text-sm"/><button onClick={addManual} className="bg-[#4CAF50] px-4 text-sm font-medium text-white">Add</button></div></div></div>
  <div className="mt-4 divide-y border border-[#E0E0E0]">{printers.map(p=><div key={p.id} className="flex items-center gap-4 p-4"><Printer size={19} className="text-[#78909C]"/><div className="flex-1"><div className="font-medium">{p.name}</div><div className="text-xs text-[#757575]">{p.ip_address||p.mac_address||p.connection_type} · {p.status}</div></div><button onClick={()=>testPrint(p)} className="border px-3 py-2 text-xs">Test print</button></div>)}{!printers.length&&<div className="p-6 text-sm text-[#757575]">No physical printers configured.</div>}</div></section>
  <Dialog open={!!modal} onOpenChange={o=>!o&&!busy&&setModal(null)}><DialogContent className="max-w-xl rounded-none"><DialogHeader><DialogTitle className="font-normal">{modal?.mode==='edit'?'Edit printer group':'Add printer group'}</DialogTitle></DialogHeader><div className="space-y-5"><input value={name} onChange={e=>setName(e.target.value)} placeholder="BAR POS" className="w-full border-b border-[#BDBDBD] px-0 py-3 outline-none focus:border-[#4CAF50]"/><div><div className="mb-2 flex items-center justify-between text-xs text-[#757575]"><span>Categories</span><span>{selectedCats.length}</span></div><div className="mb-2 flex items-center gap-2 border px-2"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search categories" className="w-full py-2 text-sm outline-none"/></div><div className="max-h-52 overflow-y-auto border">{visibleCats.map(c=><label key={c.id} className="flex items-center gap-3 border-b px-3 py-2 text-sm"><Checkbox checked={selectedCats.includes(c.id)} onCheckedChange={v=>setSelectedCats(v?[...selectedCats,c.id]:selectedCats.filter(x=>x!==c.id))}/>{c.name}</label>)}</div></div><div><div className="mb-2 text-xs text-[#757575]">Physical printers</div>{printers.map(p=><label key={p.id} className="flex items-center gap-3 py-2 text-sm"><Checkbox checked={selectedPrinters.includes(p.id)} onCheckedChange={v=>setSelectedPrinters(v?[...selectedPrinters,p.id]:selectedPrinters.filter(x=>x!==p.id))}/>{p.name}</label>)}</div></div><DialogFooter><button onClick={()=>setModal(null)} className="px-4 py-2 text-sm text-[#757575]">Cancel</button><button disabled={busy} onClick={save} className="bg-[#4CAF50] px-5 py-2 text-sm text-white">{busy?'Saving…':'Save'}</button></DialogFooter></DialogContent></Dialog>
 </div>;
}
